name: Deploy into server

on:
  push:
    branches:
      - master

env:
  NODE_VERSION: '12.x'
  DOCROOT: '/var/www/jacob.ruangtunggu.id'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: master
          fetch-depth: 1

      - name: Use Node.JS ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: |
          npm install
          npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USERNAME }}
          PORT: ${{ secrets.SERVER_PORT }}
          KEY: ${{ secrets.SERVER_KEY }}
        with:
          source: "./*,!node_modules"
          target: "${{ env.DOCROOT }}"
